---
# Install aws packages

- name: unwanted packages are removed
  package:
    name: "{{ aws_packages_remove }}"
    state: absent
  become: true
  when: aws_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ aws_packages_repos }}"
    state: "{{ aws_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ aws_packages_prereq }}"
    state: "{{ aws_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ aws_packages_install }}"
    state: "{{ aws_packages_state }}"
  become: true
