---
# Template configuration files for aws

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ aws_templates_copy }}"
  when: aws_copy_templates
